export const ALL_POST_REQUEST = "ALL_POST_REQUEST";
export const ALL_POST_SUCCESS = "ALL_POST_SUCCESS";
export const ALL_POST_FAIL = "ALL_POST_FAIL";
export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAIL = "ADD_POST_FAIL";
export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";
export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  ADD_POST:"/add-post"
};
